# Site settings
title: Afonso F
author: Afonso França de Oliveira
description: Software Engineer – Technical Team Lead – Sometimes illustrator

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/afonsof

  - title: github
    url: http://github.com/afonsof

  - title: linkedin
    url: https://linkedin.com/in/afonsof

  - title: google-plus
    url: http://plus.google.com/+afonsof

  - title: envelope-o
    url: mailto:me@afonsof.com

google_analytics_id: UA-54197665-1

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more-->
